user_pref('browser.manifestURL', "http://system.gaiamobile.org:8080/manifest.webapp");
user_pref('browser.homescreenURL', "http://system.gaiamobile.org:8080");
user_pref('network.http.max-connections-per-server', 15);
user_pref('dom.mozInputMethod.enabled', true);
user_pref('ril.debugging.enabled', false);
user_pref('dom.mms.version', 17);
user_pref('network.dns.localDomains', "gaiamobile.org,bluetooth.gaiamobile.org,browser.gaiamobile.org,calendar.gaiamobile.org,camera.gaiamobile.org,clock.gaiamobile.org,communications.gaiamobile.org,costcontrol.gaiamobile.org,email.gaiamobile.org,firefoxos-bubblepage.gaiamobile.org,fl.gaiamobile.org,fm.gaiamobile.org,gallery.gaiamobile.org,homescreen.gaiamobile.org,keyboard.gaiamobile.org,matchscreen.gaiamobile.org,music.gaiamobile.org,pdfjs.gaiamobile.org,ringtones.gaiamobile.org,setringtone.gaiamobile.org,settings.gaiamobile.org,sms.gaiamobile.org,system.gaiamobile.org,video.gaiamobile.org,wallpaper.gaiamobile.org,wappush.gaiamobile.org,marketplace-dev.allizom.org.gaiamobile.org,marketplace.allizom.org.gaiamobile.org,mochitest.gaiamobile.org,marketplace.firefox.com.gaiamobile.org,twittershare.gaiamobile.org,ds-test.gaiamobile.org,demo-keyboard.gaiamobile.org,geoloc.gaiamobile.org,membuster.gaiamobile.org,music2.gaiamobile.org,test-ime.gaiamobile.org,share-receiver.gaiamobile.org,template.gaiamobile.org,test-agent.gaiamobile.org,test-container.gaiamobile.org,test-keyboard-app.gaiamobile.org,test-otasp.gaiamobile.org,test-receiver-1.gaiamobile.org,test-receiver-2.gaiamobile.org,test-receiver-inline.gaiamobile.org,test-wappush.gaiamobile.org,uitest.gaiamobile.org");
user_pref('browser.startup.homepage', "http://system.gaiamobile.org:8080");
user_pref('startup.homepage_welcome_url', "");
user_pref('browser.shell.checkDefaultBrowser', false);
user_pref('devtools.toolbox.host', "side");
user_pref('devtools.toolbox.sidebar.width', 800);
user_pref('devtools.toolbox.selectedTool', "firefox-os-controls");
user_pref('browser.sessionstore.max_tabs_undo', 0);
user_pref('browser.sessionstore.max_windows_undo', 0);
user_pref('browser.sessionstore.restore_on_demand', false);
user_pref('browser.sessionstore.resume_from_crash', false);
user_pref('dom.mozBrowserFramesEnabled', true);
user_pref('b2g.ignoreXFrameOptions', true);
user_pref('network.disable.ipc.security', true);
user_pref('dom.ipc.tabs.disabled', true);
user_pref('browser.ignoreNativeFrameTextSelection', true);
user_pref('ui.dragThresholdX', 25);
user_pref('dom.w3c_touch_events.enabled', 1);
user_pref('dom.sms.enabled', true);
user_pref('dom.mozTCPSocket.enabled', true);
user_pref('notification.feature.enabled', true);
user_pref('dom.sysmsg.enabled', true);
user_pref('dom.mozAlarms.enabled', true);
user_pref('device.storage.enabled', true);
user_pref('device.storage.prompt.testing', true);
user_pref('notification.feature.enabled', true);
user_pref('dom.mozSettings.enabled', true);
user_pref('dom.navigator-property.disable.mozSettings', false);
user_pref('dom.mozPermissionSettings.enabled', true);
user_pref('dom.mozContacts.enabled', true);
user_pref('dom.navigator-property.disable.mozContacts', false);
user_pref('dom.global-constructor.disable.mozContact', false);
user_pref('dom.experimental_forms', true);
user_pref('dom.webapps.useCurrentProfile', true);
user_pref('bluetooth.enabled', true);
user_pref('bluetooth.visible', false);
user_pref('wifi.enabled', true);
user_pref('wifi.suspended', false);
user_pref('font.default.x-western', "sans-serif");
user_pref('font.name.serif.x-western', "Charis SIL Compact");
user_pref('font.name.sans-serif.x-western', "Feura Sans");
user_pref('font.name.monospace.x-western', "Source Code Pro");
user_pref('font.name-list.sans-serif.x-western', "Feura Sans, Roboto");
user_pref('marionette.defaultPrefs.enabled', true);
user_pref('nglayout.debug.disable_xul_cache', true);
user_pref('nglayout.debug.disable_xul_fastload', true);
user_pref('javascript.options.showInConsole', true);
user_pref('browser.dom.window.dump.enabled', true);
user_pref('dom.report_all_js_exceptions', true);
user_pref('dom.w3c_touch_events.enabled', 1);
user_pref('webgl.verbose', true);
user_pref('dom.max_script_run_time', 0);
user_pref('toolkit.identity.debug', true);
user_pref('network.http.use-cache', false);
user_pref('extensions.gaia.dir', "/Users/kevin/workspace/gaia");
user_pref('extensions.gaia.domain', "gaiamobile.org");
user_pref('extensions.gaia.port', 8080);
user_pref('extensions.gaia.appdirs', "/Users/kevin/workspace/gaia/apps/bluetooth /Users/kevin/workspace/gaia/apps/browser /Users/kevin/workspace/gaia/apps/calendar /Users/kevin/workspace/gaia/apps/camera /Users/kevin/workspace/gaia/apps/clock /Users/kevin/workspace/gaia/apps/communications /Users/kevin/workspace/gaia/apps/costcontrol /Users/kevin/workspace/gaia/apps/email /Users/kevin/workspace/gaia/apps/fastcontacts /Users/kevin/workspace/gaia/apps/firefoxos-bubblepage /Users/kevin/workspace/gaia/apps/fl /Users/kevin/workspace/gaia/apps/fm /Users/kevin/workspace/gaia/apps/gallery /Users/kevin/workspace/gaia/apps/homescreen /Users/kevin/workspace/gaia/apps/keyboard /Users/kevin/workspace/gaia/apps/matchscreen /Users/kevin/workspace/gaia/apps/music /Users/kevin/workspace/gaia/apps/pdfjs /Users/kevin/workspace/gaia/apps/ringtones /Users/kevin/workspace/gaia/apps/rocketscreen /Users/kevin/workspace/gaia/apps/scroller /Users/kevin/workspace/gaia/apps/setringtone /Users/kevin/workspace/gaia/apps/settings /Users/kevin/workspace/gaia/apps/sharedtest /Users/kevin/workspace/gaia/apps/sms /Users/kevin/workspace/gaia/apps/system /Users/kevin/workspace/gaia/apps/video /Users/kevin/workspace/gaia/apps/wallpaper /Users/kevin/workspace/gaia/apps/wappush /Users/kevin/workspace/gaia/test_external_apps/hoststubtest /Users/kevin/workspace/gaia/test_external_apps/marketplace-dev.allizom.org /Users/kevin/workspace/gaia/test_external_apps/marketplace.allizom.org /Users/kevin/workspace/gaia/test_external_apps/mochitest /Users/kevin/workspace/gaia/test_external_apps/packstubtest /Users/kevin/workspace/gaia/external-apps/m.here.com /Users/kevin/workspace/gaia/external-apps/marketplace.firefox.com /Users/kevin/workspace/gaia/showcase_apps/twittershare /Users/kevin/workspace/gaia/test_apps/ds-test /Users/kevin/workspace/gaia/test_apps/demo-keyboard /Users/kevin/workspace/gaia/test_apps/geoloc /Users/kevin/workspace/gaia/test_apps/membuster /Users/kevin/workspace/gaia/test_apps/music2 /Users/kevin/workspace/gaia/test_apps/test-ime /Users/kevin/workspace/gaia/test_apps/share-receiver /Users/kevin/workspace/gaia/test_apps/template /Users/kevin/workspace/gaia/test_apps/test-agent /Users/kevin/workspace/gaia/test_apps/test-container /Users/kevin/workspace/gaia/test_apps/test-keyboard-app /Users/kevin/workspace/gaia/test_apps/test-otasp /Users/kevin/workspace/gaia/test_apps/test-receiver-1 /Users/kevin/workspace/gaia/test_apps/test-receiver-2 /Users/kevin/workspace/gaia/test_apps/test-receiver-inline /Users/kevin/workspace/gaia/test_apps/test-wappush /Users/kevin/workspace/gaia/test_apps/uitest");
user_pref('extensions.gaia.locales_debug_path', "locales");
user_pref('extensions.gaia.official', false);
user_pref('extensions.gaia.device_pixel_suffix', "");
user_pref('extensions.gaia.app_relative_path', "apps/bluetooth apps/browser apps/calendar apps/camera apps/clock apps/communications apps/costcontrol apps/email apps/firefoxos-bubblepage apps/fl apps/fm apps/gallery apps/homescreen apps/keyboard apps/matchscreen apps/music apps/pdfjs apps/ringtones apps/setringtone apps/settings apps/sms apps/system apps/video apps/wallpaper apps/wappush test_external_apps/marketplace-dev.allizom.org test_external_apps/marketplace.allizom.org test_external_apps/mochitest external-apps/marketplace.firefox.com showcase_apps/twittershare test_apps/ds-test test_apps/demo-keyboard test_apps/geoloc test_apps/membuster test_apps/music2 test_apps/test-ime test_apps/share-receiver test_apps/template test_apps/test-agent test_apps/test-container test_apps/test-keyboard-app test_apps/test-otasp test_apps/test-receiver-1 test_apps/test-receiver-2 test_apps/test-receiver-inline test_apps/test-wappush test_apps/uitest");
user_pref('extensions.autoDisableScopes', 0);
pref("geo.gps.supl_server", "supl.izatcloud.net");
pref("geo.gps.supl_port", 22024);
pref("dom.payment.provider.0.name", "firefoxmarket");
pref("dom.payment.provider.0.description", "marketplace.firefox.com");
pref("dom.payment.provider.0.uri", "https://marketplace.firefox.com/mozpay/?req=");
pref("dom.payment.provider.0.type", "mozilla/payments/pay/v1");
pref("dom.payment.provider.0.requestMethod", "GET");
pref("dom.payment.skipHTTPSCheck", true);

pref("dom.payment.provider.1.name", "firefoxmarketdev");
pref("dom.payment.provider.1.description", "marketplace-dev.allizom.org");
pref("dom.payment.provider.1.uri", "https://marketplace-dev.allizom.org/mozpay/?req=");
pref("dom.payment.provider.1.type", "mozilla-dev/payments/pay/v1");
pref("dom.payment.provider.1.requestMethod", "GET");

pref("dom.payment.provider.2.name", "firefoxmarketstage");
pref("dom.payment.provider.2.description", "marketplace.allizom.org");
pref("dom.payment.provider.2.uri", "https://marketplace.allizom.org/mozpay/?req=");
pref("dom.payment.provider.2.type", "mozilla-stage/payments/pay/v1");
pref("dom.payment.provider.2.requestMethod", "GET");


pref("marionette.defaultPrefs.enabled", true);
pref("marionette.defaultPrefs.port", 64943);